export type Plan = 'free' | 'solo' | 'swarm' | 'enterprise'
export type EnrichmentLevel = 'none' | 'basic' | 'advanced' | 'custom'
export type Entitlements = { scansPerMonth:number; leadsPerMonth:number; draftsPerMonth:number; exportsEnabled:boolean; gmailSendingEnabled:boolean; inboxMonitoringEnabled:boolean; recurringAgentsEnabled:boolean; maxActiveAgents:number; maxWorkspaces:number; enrichmentLevel:EnrichmentLevel; crmExportEnabled:boolean; prioritySupport:boolean }
export type FeatureKey = 'exportCsv'|'exportJson'|'revealLeads'|'generateDrafts'|'recurringAgents'|'activeAgents'|'connectGmail'|'sendEmail'|'inboxMonitoring'|'crmExport'|'workspaces'|'advancedEnrichment'
export const PLAN_ENTITLEMENTS: Record<Plan, Entitlements> = { free:{scansPerMonth:1,leadsPerMonth:25,draftsPerMonth:5,exportsEnabled:false,gmailSendingEnabled:false,inboxMonitoringEnabled:false,recurringAgentsEnabled:false,maxActiveAgents:0,maxWorkspaces:1,enrichmentLevel:'none',crmExportEnabled:false,prioritySupport:false}, solo:{scansPerMonth:10,leadsPerMonth:1000,draftsPerMonth:250,exportsEnabled:true,gmailSendingEnabled:false,inboxMonitoringEnabled:false,recurringAgentsEnabled:true,maxActiveAgents:1,maxWorkspaces:1,enrichmentLevel:'basic',crmExportEnabled:false,prioritySupport:false}, swarm:{scansPerMonth:Number.POSITIVE_INFINITY,leadsPerMonth:10000,draftsPerMonth:2500,exportsEnabled:true,gmailSendingEnabled:true,inboxMonitoringEnabled:true,recurringAgentsEnabled:true,maxActiveAgents:10,maxWorkspaces:5,enrichmentLevel:'advanced',crmExportEnabled:true,prioritySupport:true}, enterprise:{scansPerMonth:Number.POSITIVE_INFINITY,leadsPerMonth:Number.POSITIVE_INFINITY,draftsPerMonth:Number.POSITIVE_INFINITY,exportsEnabled:true,gmailSendingEnabled:true,inboxMonitoringEnabled:true,recurringAgentsEnabled:true,maxActiveAgents:Number.POSITIVE_INFINITY,maxWorkspaces:Number.POSITIVE_INFINITY,enrichmentLevel:'custom',crmExportEnabled:true,prioritySupport:true} }
const featurePlan: Record<FeatureKey, Plan> = { exportCsv:'solo',exportJson:'solo',revealLeads:'solo',generateDrafts:'solo',recurringAgents:'solo',activeAgents:'solo',connectGmail:'swarm',sendEmail:'swarm',inboxMonitoring:'swarm',crmExport:'swarm',workspaces:'swarm',advancedEnrichment:'swarm' }
export const getPlanEntitlements = (plan:Plan)=>PLAN_ENTITLEMENTS[plan]
export const getUpgradePlanForFeature = (featureKey:FeatureKey)=>featurePlan[featureKey]
export function canUseFeature(plan:Plan, featureKey:FeatureKey){const e=getPlanEntitlements(plan); if(featureKey==='exportCsv'||featureKey==='exportJson') return e.exportsEnabled; if(featureKey==='connectGmail'||featureKey==='sendEmail') return e.gmailSendingEnabled; if(featureKey==='inboxMonitoring') return e.inboxMonitoringEnabled; if(featureKey==='recurringAgents') return e.recurringAgentsEnabled; if(featureKey==='crmExport') return e.crmExportEnabled; if(featureKey==='advancedEnrichment') return e.enrichmentLevel==='advanced'||e.enrichmentLevel==='custom'; return true}
export const hasReachedLimit=(plan:Plan, usageKey:'scansPerMonth'|'leadsPerMonth'|'draftsPerMonth'|'maxActiveAgents'|'maxWorkspaces', currentUsage:number)=> currentUsage >= getPlanEntitlements(plan)[usageKey]
export function getPaywallCopy(featureKey: FeatureKey, currentPlan: Plan){const requiredPlan=getUpgradePlanForFeature(featureKey); if(requiredPlan==='enterprise') return {title:'Custom growth infrastructure',body:'Enterprise supports higher volume, custom workflows, CRM integrations, and dedicated support.',cta:'Talk to sales',requiredPlan}; if(featureKey==='exportCsv'||featureKey==='exportJson') return {title:'Unlock exports',body:'Export your leads, drafts, and scan results to CSV or JSON with Solo.',cta:'Upgrade to Solo',requiredPlan}; if(featureKey==='connectGmail'||featureKey==='sendEmail') return {title:'Send outreach from AgentN',body:'Swarm unlocks Gmail sending, reply monitoring, and daily execution agents.',cta:'Upgrade to Swarm',requiredPlan}; if(featureKey==='inboxMonitoring') return {title:'Monitor replies automatically',body:'Swarm watches your inbox, detects replies, and surfaces follow-up opportunities.',cta:'Upgrade to Swarm',requiredPlan}; if(featureKey==='recurringAgents') return {title:'Run growth agents on autopilot',body:'Solo unlocks recurring scans. Swarm unlocks higher-volume daily execution.',cta:currentPlan==='solo'?'Upgrade to Swarm':'Upgrade to Solo',requiredPlan}; if(featureKey==='revealLeads') return {title:'Reveal more qualified leads',body:'Upgrade to Solo to unlock 1,000 leads/month, exports, and recurring scans.',cta:'Upgrade to Solo',requiredPlan}; if(featureKey==='advancedEnrichment') return {title:'Unlock advanced enrichment',body:'Swarm enriches leads with deeper company, role, and intent data.',cta:'Upgrade to Swarm',requiredPlan}; return {title:'Custom growth infrastructure',body:'Enterprise supports higher volume, custom workflows, CRM integrations, and dedicated support.',cta:requiredPlan==='swarm'?'Upgrade to Swarm':'Upgrade to Solo',requiredPlan}}
