'use client'
import { useState } from 'react'
import { useMvp } from '@/lib/mvpStore'

export default function ProofOfWorkTable(){
 const {state, createContractFromTask}=useMvp(); const [sel,setSel]=useState<any>(null)
 const rows=state.proofRecords
 const toCsv = (leads:any[] = []) => {
  const headers = ['Company','Website','Contact','Role','Email','Signal','Fit Score','Suggested Opener','Source']
  const body = leads.map(l => [l.companyName, l.website ?? '', l.contactName ?? '', l.role ?? '', l.email ?? '', (l.buyingSignals??[]).join('|'), l.fitScore ?? '', l.personalizedOpener ?? '', l.sourceUrl ?? ''].map(v => `"${String(v).replaceAll('"', '""')}"`).join(','))
  return [headers.join(','), ...body].join('\n')
 }
 return <div className='page-scroll'><div className='page-header'><div><div className='page-title'>PROOF OF WORK</div></div></div><div className='page-body'>{rows.length===0?<div className='empty-state'><div className='empty-title'>No proof records yet</div></div>:<div className='table-wrap'><table className='tbl'><thead><tr><th>TASK</th><th>AGENT</th><th>TYPE</th><th>COST</th><th>STATUS</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id} onClick={()=>setSel(r)} style={{cursor:'pointer'}}><td>{r.taskId}</td><td>{r.agentName}</td><td>{r.type}</td><td>${r.cost?.toFixed(2)}</td><td><span className='badge b-green'>{r.status}</span></td></tr>)}</tbody></table></div>}</div>{sel&&<div className='modal-overlay open' onClick={()=>setSel(null)}><div className='modal' onClick={e=>e.stopPropagation()}><h3>Proof Detail</h3><div>Task ID: {sel.taskId}</div><div>Status: Verified</div><div>Proof hash: {sel.hash}</div><div>Source URLs: {(sel.proofMeta?.sourceUrls ?? []).join(', ') || 'sample mode'}</div><div>Fetch stats: {sel.proofMeta?.successfulFetchCount ?? 0} success / {sel.proofMeta?.failedFetchCount ?? 0} failed</div><div>Leads found: {sel.proofMeta?.leadsFound ?? sel.artifact?.leads?.length ?? 0} · Qualified: {sel.proofMeta?.qualifiedLeads ?? 0}</div><div>Validation checks: {(sel.proofMeta?.validationChecks ?? []).join(', ')}</div>
{sel.artifact?.leads?.length ? <div className='table-wrap'><table className='tbl'><thead><tr><th>Company</th><th>Website</th><th>Contact</th><th>Role</th><th>Email</th><th>Signal</th><th>Fit Score</th><th>Suggested Opener</th><th>Source</th></tr></thead><tbody>{sel.artifact.leads.map((l:any)=><tr key={l.id}><td>{l.companyName}</td><td>{l.website}</td><td>{l.contactName ?? '—'}</td><td>{l.role ?? '—'}</td><td>{l.email ?? '—'}</td><td>{(l.buyingSignals??[])[0] ?? '—'}</td><td>{l.fitScore} ({l.scoreGrade})</td><td>{l.personalizedOpener}</td><td>{l.sourceUrl}</td></tr>)}</tbody></table></div> : <div className='artifact-box'>{JSON.stringify(sel.artifact,null,2)}</div>}
<div className='modal-actions'><button className='mbtn-ok' onClick={()=>{const blob=new Blob([JSON.stringify(sel.artifact)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`${sel.taskId}.json`; a.click()}}>Export JSON</button><button className='mbtn-ok' onClick={()=>{const blob=new Blob([toCsv(sel.artifact?.leads)],{type:'text/csv'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`${sel.taskId}.csv`; a.click()}}>Export CSV</button><button className='mbtn-ok' onClick={()=>createContractFromTask(sel.taskId)}>Create Weekly Lead Contract</button></div></div></div>}</div>
}
