'use client'
import { useState } from 'react'
import { useMvp } from '@/lib/mvpStore'

export default function ProofOfWorkTable(){
 const {state, createContractFromTask}=useMvp(); const [sel,setSel]=useState<any>(null)
 const rows=state.proofRecords
 return <div className='page-scroll'><div className='page-header'><div><div className='page-title'>PROOF OF WORK</div></div></div><div className='page-body'>{rows.length===0?<div className='empty-state'><div className='empty-title'>No proof records yet</div></div>:<div className='table-wrap'><table className='tbl'><thead><tr><th>TASK</th><th>AGENT</th><th>TYPE</th><th>COST</th><th>STATUS</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id} onClick={()=>setSel(r)} style={{cursor:'pointer'}}><td>{r.taskId}</td><td>{r.agentName}</td><td>{r.type}</td><td>${r.cost?.toFixed(2)}</td><td><span className='badge b-green'>{r.status}</span></td></tr>)}</tbody></table></div>}</div>{sel&&<div className='modal-overlay open' onClick={()=>setSel(null)}><div className='modal' onClick={e=>e.stopPropagation()}><h3>Proof Detail</h3><div>Task ID: {sel.taskId}</div><div>Status: Verified</div><div>Proof hash: {sel.hash}</div><div>Validation: Source completeness, Duplicate removal, Format valid, Budget respected, Runtime within SLA, Human review optional.</div><div className='artifact-box'>{JSON.stringify(sel.artifact,null,2)}</div><div className='modal-actions'><button className='mbtn-ok' onClick={()=>{const blob=new Blob([JSON.stringify(sel.artifact)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`${sel.taskId}.json`; a.click()}}>Download Artifact</button><button className='mbtn-ok' onClick={()=>createContractFromTask(sel.taskId)}>Create Contract</button></div></div></div>}</div>
}
